# nav2_params_real.yaml (実機用)

local_costmap:
  local_costmap:
    ros__parameters:
      # ロボットの形 (長方形の場合)
      footprint: "[ [0.25, 0.18], [0.25, -0.18], [-0.25, -0.18], [-0.25, 0.18] ]" 
      # または半径 (円形として扱う場合、少し大きめに)
      # robot_radius: 0.25 
      
      inflation_layer:
        # 実機は壁にぶつかると痛いので、少し余裕を持つ
        inflation_radius: 0.55